version: "3"
services:
  postgres:
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - .postgres:/var/lib/postgresql/data
  api:
    build: .
    user: "1000:1000"
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - postgres
volumes:
  node_modules: