### needs vscode extension Rest Client

GET http://localhost:3001/

###
POST http://localhost:3001/oauth2/token HTTP/1.1
content-type: application/json

{
    "client_id": "client_id",
    "client_secret": "oauthsecret"
}

###

POST http://localhost:3001/resource/v1/protheus/employee HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRfaWQiOiJjbGllbnRfaWQiLCJpYXQiOjE2NjMyMDM2MTV9.5LEpPwM_B-IYUqLMRLRUpnMv9uKTAs3X2Sv3du4KZzw

{
    "cpf": "05785771195"
}

###
